// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDataEF;

#nullable disable

namespace My.Migrations
{
    [DbContext(typeof(MyDB))]
    [Migration("20230604162244_Ketiga")]
    partial class Ketiga
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            
        }
    }
}
