version: "3.7"
services:
  dotnet:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    container_name: my-app-dotnet
    restart: unless-stopped
    working_dir: /app/MyApp
    command: dotnet watch run --launch-profile http --non-interactive
    ports:
      - 5001:5001
    volumes:
      - ./extra:/app/extra
      - ./logs:/app/logs
      - ./MyApp:/app/MyApp
      - ./MyLibrary:/app/MyLibrary
      - ./MyDataEF:/app/MyDataEF
    networks:
      - my_app_project

  # nginx:
  #   image: nginx:1.17-alpine
  #   container_name: my-app-nginx
  #   restart: unless-stopped
  #   ports:
  #     - 5002:80
  #   volumes:
  #     - ./extra/nginx:/etc/nginx/conf.d
  #   networks:
  #     - my_app_project
      
      
networks:
  my_app_project:
    driver: bridge
