version: "3.7"
services:
  dotnet:
    build:
      context: ./
      dockerfile: docker-compose.prod.dockerfile
    image: mcr.microsoft.com/dotnet/aspnet:my-app-7.0
    container_name: my-app-dotnet
    restart: unless-stopped
    working_dir: /app
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001;
    networks:
      - my_app_project
    volumes:
      - ./logs/test:/extra
      - ./logs/test:/logs

  # nginx:
  #   image: nginx:1.17-alpine
  #   container_name: my-app-nginx
  #   restart: unless-stopped
  #   ports:
  #     - 5002:80
  #   volumes:
  #     - ./extra/nginx:/etc/nginx/conf.d
  #   networks:
  #     - my_app_project
      
      
networks:
  my_app_project:
    driver: bridge
